# Generated by Django 5.2.1 on 2025-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=50, unique=True)),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('available_copies', models.PositiveIntegerField()),
                ('language', models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic')], max_length=10)),
                ('book_image', models.ImageField(upload_to='book_images/')),
            ],
        ),
    ]
