# Generated by Django 5.2.1 on 2025-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_remove_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
