# Generated by Django 5.2.1 on 2025-05-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_remove_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
